FRAME_TIME = 1 / 60
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
CELL_IMG_WIDTH = 20
CELL_IMG_HEIGHT = 20



CELL_SPAWN_BORDER_X = WINDOW_WIDTH/10
CELL_SPAWN_BORDER_Y = WINDOW_HEIGHT/10

-- cell generation boundaries
BoundaryLeft = CELL_SPAWN_BORDER_X + CELL_IMG_WIDTH / 2
BoundaryRight = WINDOW_WIDTH - CELL_SPAWN_BORDER_X - CELL_IMG_WIDTH / 2
BoundaryTop = CELL_SPAWN_BORDER_Y + CELL_IMG_HEIGHT / 2
BoundaryBottom = WINDOW_HEIGHT - CELL_SPAWN_BORDER_Y - CELL_IMG_HEIGHT / 2
